# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 157b2ca7c370fb2c46d8e2f162879f9b094490e9310033e8ffcd267c6ea612f09ca6821db30b70e6468831b6a72e8bdcae159105d8e4efdd47543aad1960e28a

test:
  secret_key_base: 33009eae6e18295d47d7bedb783c8e474dd92feb5d31a63288bbf698e669bffe7e9ea575e91d4d1428099910883107ec5c9995e7973e21efc85e9f7882ceb9fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
